[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://victorsg1.github.io"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
